/**
 * Created by hyc on 16-12-31.
 */
export const SET_SESSION = 'SET_SESSION'
export const SET_USER = 'SET_USER'
export const MERGE_FOLLOWINGS = 'MERGE_FOLLOWINGS'
export const MERGE_ACTIVITIES = 'MERGE_ACTIVITIES'


export const SET_ACTIVITIES_REQUEST_IN_PROCESS = 'SET_ACTIVITIES_REQUEST_IN_PROCESS'
export const SET_ACTIVITIES_REQUEST_NEXT_HREF = 'SET_ACTIVITIES_REQUEST_NEXT_HREF'

export const SET_IS_PLAYING = 'SET_IS_PLAYING'
export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK'


