/**
 * Created by hyc on 16-12-31.
 */
export const SET_SESSION = 'SET_SESSION'
export const SET_USER = 'SET_USER'
export const MERGE_USER_ENTITIES = 'MERGE_USER_ENTITIES'
export const MERGE_TRACK_ENTITIES = 'MERGE_TRACK_ENTITIES'
export const MERGE_SONGS_ENTITIES = 'MERGE_SONGS_ENTITIES'
export const SET_FOLLOWINGS = 'SET_FOLLOWINGS'
export const SET_FOLLOWINGS_REQUEST_NEXT_HREF = 'SET_FOLLOWINGS_REQUEST_NEXT_HREF'

export const SYNC_ENTITEIS = 'SYNC_ENTITEIS'

export const SET_FOLLOWERS = 'SET_FOLLOWERS'
export const SET_ACTIVITIES = 'SET_ACTIVITIES'
export const SET_FAVORITES = 'SET_FAVORITES'

export const MERGE_FOLLOWINGS = 'MERGE_FOLLOWINGS'
export const MERGE_ACTIVITIES = 'MERGE_ACTIVITIES'

export const MERGE_FOLLOWERS = 'MERGE_FOLLOWERS'
export const SET_FOLLOWERS_REQUEST_NEXT_HREF = 'SET_FOLLOWERS_REQUEST_NEXT_HREF'

export const SET_ACTIVITIES_REQUEST_NEXT_HREF = 'SET_ACTIVITIES_REQUEST_NEXT_HREF'

export const SET_IS_PLAYING = 'SET_IS_PLAYING'
export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK'

export const SET_TRACK_IN_PLAYLIST = 'SET_TRACK_IN_PLAYLIST'

export const REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST'

export const DEACTIVE_TRACK = 'DEACTIVE_TRACK'

export const SET_IS_OPEN_PLAYLIST = 'SET_IS_OPEN_PLAYLIST'

export const MERGE_FAVORITES = 'MERGE_FAVORITES'
export const SET_FAVORITES_REQUEST_NEXT_HREF = 'SET_FAVORITES_REQUEST_NEXT_HREF'

// browse
export const SET_ACTIVITIES_BY_GENRE_NEXT_HREF = 'SET_ACTIVITIES_BY_GENRE_NEXT_HREF'
export const MERGE_ACTIVITIES_BY_GENRE = 'MERGE_ACTIVITIES_BY_GENRE'

// like
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'

// request
export const SET_REQUESTTYPE_IN_PROCESS = 'SET_REQUESTTYPE_IN_PROCESS'
// paginate
export const SET_PAGINATE_LINK = 'SET_PAGINATE_LINK'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'
