export const PLAYLISTTYPE = 'PLAYLISTTYPE'
export const FAVORITESTYPE = 'FAVORITESTYPE'
export const FOLLOWERSTYPE = 'FOLLOWERSTYPE'
export const FOLLOWINGSTYPE = 'FOLLOWINGSTYPE'
export const COMMENTSTYPE = 'COMMENTSTYPE'
export const SHUFFLETYPE = 'SHUFFLETYPE'
export const ADJUSTVOLUME = 'ADJUSTVOLUME';
export const AUDIOMUTE = 'AUDIOMUTE';
